window.ETERNIZE_PRODUCTS = [
  {
    slug: "cartoon-ia",
    title: "Cartoon IA",
    category: "IA e interação",
    accent: "#e2007a",
    image: "assets/site/cartoon-ia.webp",
    alt: "Cartoon IA com identidade de marca",
    summary: "Transforma a imagem do convidado em uma arte ilustrativa instantânea, colorida e compartilhável.",
    description:
      "Inovador, oferece uma experiência divertida e interativa, permitindo que o convidado se transforme em um cartoon de maneira instantânea e cativante. Com apenas um clique, a imagem é transformada em uma obra de arte ilustrativa, com cores vibrantes e estilo único.",
    features: ["Transformação instantânea por IA", "Arte com identidade visual do evento", "Conteúdo pronto para redes sociais"],
    ideal: "Eventos corporativos, ativações de marca, feiras, lançamentos e ações que pedem alto impacto visual.",
    gallery: ["assets/site/cartoon-ia.webp", "assets/site/totem-mobile.webp", "assets/site/portfolio-page-1.webp"],
  },
  {
    slug: "totem-jogos",
    title: "Totem de jogos",
    category: "Engajamento",
    accent: "#e2007a",
    image: "assets/site/totem-games.webp",
    alt: "Totem interativo com jogos",
    summary: "Quiz, memória, roleta digital, premiações, leads e mídia do evento em uma experiência interativa.",
    description:
      "Totem interativo com temas e elementos da identidade visual do evento. Inclui jogos personalizados, como quiz do casal, debutante ou empresa, jogo da memória e roleta digital, engajando adultos e crianças de forma divertida. Premiações especiais tornam a experiência ainda mais envolvente, com captação de leads e vídeos de propaganda do evento.",
    features: ["Jogos personalizados", "Captação de leads", "Premiações e mídia no totem"],
    ideal: "Stands, ações promocionais, eventos internos, casamentos, aniversários e ativações que precisam de participação.",
    gallery: ["assets/site/totem-games.webp", "assets/site/mosaico.webp", "assets/site/terminal-instagram.webp"],
  },
  {
    slug: "mosaico-fotos",
    title: "Mosaico de fotos",
    category: "Corporativo",
    accent: "#0274bc",
    image: "assets/site/mosaico.webp",
    alt: "Mosaico de fotos corporativo",
    summary: "As fotos dos participantes formam uma logo, frase ou imagem final de alto valor simbólico.",
    description:
      "As imagens são impressas com um filtro especial e, ao serem unidas, formam a logo ou frase da empresa. A ideia é transmitir que cada colaborador, com sua participação, contribui para formar a força e a identidade da marca.",
    features: ["Formação de logo ou frase", "Participação coletiva", "Entrega visual para marca"],
    ideal: "Eventos corporativos, endomarketing, convenções, feiras e campanhas internas.",
    gallery: ["assets/site/mosaico.webp", "assets/site/portfolio-page-2.webp", "assets/site/totem-fotos.webp"],
  },
  {
    slug: "totem-fotos",
    title: "Totem de fotos",
    category: "Fotos impressas",
    accent: "#ffc400",
    image: "assets/site/totem-fotos.webp",
    alt: "Totem de fotos para evento",
    summary: "Fotos impressas, fotos digitais e GIFs com compartilhamento imediato por QR Code.",
    description:
      "O totem é móvel, super interativo e dinâmico. O monitor pode ir até o convidado, permitindo fotografar na própria mesa, na pista de dança ou na mesa principal da decoração. Além das fotos impressas, há opção de fotos digitais e GIFs animados, compartilhados na hora por QR Code para postagem nas redes sociais.",
    features: ["Fotos impressas na hora", "GIFs e fotos digitais", "Compartilhamento por QR Code"],
    ideal: "Casamentos, formaturas, aniversários, festas sociais, eventos empresariais e recepções.",
    gallery: ["assets/site/totem-fotos.webp", "assets/site/totem-mobile.webp", "assets/site/polaroid.webp"],
  },
  {
    slug: "totem-mobile-slim",
    title: "Totem Mobile/Slim",
    category: "Mobile e slim",
    accent: "#df1018",
    image: "assets/site/totem-mobile.webp",
    alt: "Totem mobile slim com ring light",
    summary: "Estrutura moderna com fotos impressas e digitais, GIFs e identidade visual personalizada.",
    description:
      "Uma nova versão do Totem Slim, com fotos impressas e digitais, fotos e GIFs personalizados e compartilhamento por QR Code para postagens imediatas. A estrutura Slim é mais moderna e pode receber personalização com a identidade visual do evento.",
    features: ["Estrutura compacta", "Fotos e GIFs personalizados", "Personalização visual do evento"],
    ideal: "Eventos com pouco espaço, ativações modernas, festas sociais, ações de marca e recepções.",
    gallery: ["assets/site/totem-mobile.webp", "assets/site/totem-fotos.webp", "assets/site/portfolio-page-4.webp"],
  },
  {
    slug: "telefone-retro",
    title: "Telefone Retrô",
    category: "Memória afetiva",
    accent: "#f15a24",
    image: "assets/site/telefone-retro.webp",
    alt: "Telefone retrô para áudio recordações",
    summary: "Convidados gravam mensagens de voz para eternizar histórias, votos e emoções do evento.",
    description:
      "Os convidados gravam um áudio por meio de uma ligação no telefone retrô. A Eternize registra esse momento e preserva a emoção transmitida pela voz em uma lembrança especial do evento.",
    features: ["Mensagens de voz dos convidados", "Experiência afetiva", "Registro emocional do momento"],
    ideal: "Casamentos, aniversários, formaturas, eventos familiares e celebrações com forte carga emocional.",
    gallery: ["assets/site/telefone-retro.webp", "assets/site/polaroid.webp", "assets/site/espelho-magico.webp"],
  },
  {
    slug: "maquina-laser",
    title: "Máquina a laser",
    category: "Brinde ao vivo",
    accent: "#0aa64b",
    image: "assets/site/laser.webp",
    alt: "Gravação a laser personalizada",
    summary: "Grava nomes, logos e identidade visual em copos, garrafas, chaveiros e outros itens na hora.",
    description:
      "Com a máquina de personalizados, é possível gravar nome, identidade visual e logo em copos, garrafas, chaveiros e outros itens na hora. Uma lembrança marcante para surpreender convidados e ativar a marca.",
    features: ["Gravação ao vivo", "Brindes personalizados", "Logo e identidade visual aplicados"],
    ideal: "Ativações de marca, feiras, eventos corporativos, lançamentos e ações promocionais.",
    gallery: ["assets/site/laser.webp", "assets/site/brindes-copos.webp", "assets/site/brindes-chaveiros.webp"],
  },
  {
    slug: "maquina-brindes",
    title: "Máquina de brindes",
    category: "Experiência lúdica",
    accent: "#0aa64b",
    image: "assets/site/maquina-brindes.webp",
    alt: "Máquina de brindes personalizada",
    summary: "Máquina temática com mimos personalizados, filas divertidas e alto potencial de fotos.",
    description:
      "A clássica máquina de pegar brindes e bichinhos de pelúcia ganha uma repaginada com decoração temática e mimos personalizados. Garante diversão, engajamento nas filas e muitos cliques para fotos.",
    features: ["Máquina temática", "Mimos personalizados", "Experiência divertida e fotografável"],
    ideal: "Ações promocionais, stands, eventos infantis, ativações corporativas e experiências de marca.",
    gallery: ["assets/site/maquina-brindes.webp", "assets/site/brindes-porta-retratos.webp", "assets/site/brindes-crachas.webp"],
  },
  {
    slug: "cabine-vento",
    title: "Cabine de vento",
    category: "Prêmios",
    accent: "#0274bc",
    image: "assets/site/cabine-vento.webp",
    alt: "Cabine de vento para prêmios",
    summary: "Experiência imersiva para sorteios, tickets, brindes e frases personalizadas.",
    description:
      "A cabine de vento é uma experiência imersiva e super divertida. Os convidados entram, tentam retirar um ticket na sorte e descobrem o brinde ou frase escrita. Ela é personalizada de acordo com o evento e pode ser combinada com vídeos em slow motion com moldura personalizada.",
    features: ["Dinâmica de sorteio", "Personalização do evento", "Integração com vídeo e brindes"],
    ideal: "Promoções, ativações de marca, feiras, festas corporativas e eventos com premiação.",
    gallery: ["assets/site/cabine-vento.webp", "assets/site/slow-motion.webp", "assets/site/maquina-brindes.webp"],
  },
  {
    slug: "cabine-slow-motion",
    title: "Cabine Slow Motion",
    category: "Conteúdo",
    accent: "#ffc400",
    image: "assets/site/slow-motion.webp",
    alt: "Cabine slow motion",
    summary: "Vídeos em câmera lenta e rápida, moldura personalizada e compartilhamento imediato.",
    description:
      "A Cabine Slow Motion traz inovação para fotos e vídeos, com uma experiência totalmente personalizada para o evento. Os vídeos podem ser em câmera lenta e rápida, com moldura personalizada e compartilhamento imediato para postagens nas redes.",
    features: ["Vídeos slow e fast motion", "Moldura personalizada", "Compartilhamento imediato"],
    ideal: "Festas sociais, formaturas, casamentos, ativações de marca e eventos que pedem conteúdo dinâmico.",
    gallery: ["assets/site/slow-motion.webp", "assets/site/cabine-vento.webp", "assets/site/tunel-eternize.webp"],
  },
  {
    slug: "cabine-360",
    title: "Cabine 360",
    category: "Imersão",
    accent: "#df1018",
    image: "assets/site/cabine-360.webp",
    alt: "Cabine 360 personalizada",
    summary: "Vídeos superanimados com trilha, efeitos personalizados e cenário temático.",
    description:
      "Os convidados sobem na plataforma e registram vídeos superanimados, com trilha sonora típica, efeitos personalizados e cenário temático. Uma lembrança divertida, moderna e perfeita para viralizar.",
    features: ["Vídeo 360°", "Trilha e efeitos personalizados", "Cenário temático"],
    ideal: "Casamentos, formaturas, eventos de marca, festas sociais e ações com foco em redes sociais.",
    gallery: ["assets/site/cabine-360.webp", "assets/site/plataforma-360.webp", "assets/site/tunel-eternize.webp"],
  },
  {
    slug: "plataforma-360",
    title: "Plataforma 360",
    category: "Social e marca",
    accent: "#0aa64b",
    image: "assets/site/plataforma-360.webp",
    alt: "Plataforma 360 para eventos",
    summary: "Vídeos 360 com efeitos de câmera, cenário personalizado e alto potencial de compartilhamento.",
    description:
      "Os vídeos 360 com efeitos de câmera lenta e rápida são uma forma atual de eternizar eventos sociais ou ativar uma marca. Com cenário personalizado com cores e elementos da identidade visual, a experiência fica mais imersiva, privativa e incrível.",
    features: ["Cenário personalizado", "Efeitos de câmera", "Conteúdo para social media"],
    ideal: "Eventos sociais, ativações de marca, lançamentos, feiras e experiências com foco em viralização.",
    gallery: ["assets/site/plataforma-360.webp", "assets/site/cabine-360.webp", "assets/site/portfolio-page-5.webp"],
  },
  {
    slug: "tunel-eternize",
    title: "Túnel Eternize",
    category: "LED e impacto",
    accent: "#f15a24",
    image: "assets/site/tunel-eternize.webp",
    alt: "Túnel Eternize com luzes",
    summary: "Cabine cheia de LEDs para criar conteúdo marcante, imersivo e compartilhável.",
    description:
      "Uma experiência divertida em que os convidados entram em uma cabine cheia de LEDs. Ideal para gerar conteúdo marcante, imersivo e muito compartilhável.",
    features: ["Cabine com LEDs", "Conteúdo de alto impacto", "Experiência imersiva"],
    ideal: "Festas, lançamentos, ativações noturnas, eventos sociais e marcas que querem presença visual forte.",
    gallery: ["assets/site/tunel-eternize.webp", "assets/site/slow-motion.webp", "assets/site/plataforma-360.webp"],
  },
  {
    slug: "iphonao-eternize",
    title: "Iphonão Eternize",
    category: "Alternativa compacta",
    accent: "#df1018",
    image: "assets/site/iphonao.webp",
    alt: "Iphonão Eternize",
    summary: "Alternativa compacta para fotos amplas, sem limite de pessoas na sessão.",
    description:
      "O Iphonão é uma ótima alternativa à cabine de fotos, utilizando um espaço menor e oferecendo maior amplitude nas fotos. Não há limite de pessoas para tirar fotos juntas na sessão.",
    features: ["Ocupa menos espaço", "Fotos amplas", "Ideal para grupos"],
    ideal: "Eventos com circulação intensa, festas, recepções, stands e espaços compactos.",
    gallery: ["assets/site/iphonao.webp", "assets/site/totem-fotos.webp", "assets/site/totem-mobile.webp"],
  },
  {
    slug: "espelho-magico",
    title: "Espelho Mágico",
    category: "Charme",
    accent: "#e2007a",
    image: "assets/site/espelho-magico.webp",
    alt: "Espelho mágico em moldura dourada",
    summary: "Fotos reveladas na hora em uma experiência elegante, interativa e visualmente bonita.",
    description:
      "Os convidados fazem poses de frente ao espelho e a foto é revelada na hora. A experiência mistura encanto, magia e diversão, ocupa pouco espaço no evento e deixa o ambiente mais bonito.",
    features: ["Experiência interativa", "Fotos reveladas na hora", "Visual elegante para o evento"],
    ideal: "Casamentos, debutantes, aniversários, eventos sociais sofisticados e recepções.",
    gallery: ["assets/site/espelho-magico.webp", "assets/site/espelho-vintage.webp", "assets/site/hero-espelho.webp"],
  },
  {
    slug: "espelho-magico-vintage",
    title: "Espelho Mágico Vintage",
    category: "Vintage ou black",
    accent: "#0274bc",
    image: "assets/site/espelho-vintage.webp",
    alt: "Espelho vintage em evento",
    summary: "Design vintage ou estrutura black para fotos impressas na hora com moldura personalizada.",
    description:
      "O espelho com design vintage também conta com opção em estrutura moderna toda em preto. Ele adiciona charme ao evento com fotos impressas na hora e moldura personalizada.",
    features: ["Opção vintage ou black", "Moldura personalizada", "Fotos impressas na hora"],
    ideal: "Eventos sociais, casamentos, festas temáticas, recepções e ambientes com proposta decorativa.",
    gallery: ["assets/site/espelho-vintage.webp", "assets/site/espelho-magico.webp", "assets/site/hero-espelho.webp"],
  },
  {
    slug: "polaroid-lembrancas",
    title: "Polaroid lembranças",
    category: "Recepção",
    accent: "#ffc400",
    image: "assets/site/polaroid.webp",
    alt: "Polaroid lembranças em evento",
    summary: "Fotos instantâneas na chegada ou durante todo o evento, entregues aos convidados.",
    description:
      "Há duas opções para os pacotes de Polaroid Lembrança: recepção do evento, fotografando os convidados na chegada e entregando as fotos ao longo da celebração, ou cobertura durante todo o período com fotos instantâneas.",
    features: ["Fotos instantâneas", "Entrega durante o evento", "Opção recepção ou cobertura completa"],
    ideal: "Casamentos, aniversários, formaturas, recepções e eventos que querem lembrança física afetiva.",
    gallery: ["assets/site/polaroid.webp", "assets/site/telefone-retro.webp", "assets/site/totem-fotos.webp"],
  },
  {
    slug: "cabine-tradicional",
    title: "Cabine tradicional",
    category: "Privacidade",
    accent: "#df1018",
    image: "assets/site/cabine-tradicional.webp",
    alt: "Cabine tradicional de fotos",
    summary: "Cabine interativa com privacidade e personalização lateral para pessoas ou marcas.",
    description:
      "Cabine de fotos totalmente interativa, em que os convidados podem tirar fotos com mais privacidade. A lateral pode ser personalizada com foto dos noivos, debutantes, aniversariantes ou propagandas.",
    features: ["Mais privacidade", "Personalização lateral", "Experiência clássica de cabine"],
    ideal: "Casamentos, debutantes, aniversários, festas corporativas e ações com comunicação visual.",
    gallery: ["assets/site/cabine-tradicional.webp", "assets/site/cabine-inflavel.webp", "assets/site/portfolio-page-2.webp"],
  },
  {
    slug: "cabine-inflavel",
    title: "Cabine inflável",
    category: "Grupos",
    accent: "#0aa64b",
    image: "assets/site/cabine-inflavel.webp",
    alt: "Cabine inflável Eternize",
    summary: "Espaço reservado e amplo para poses, acessórios e fotos em grupo com privacidade.",
    description:
      "Com amplo espaço interno, a Cabine Inflável Eternize é ideal para festas corporativas, formaturas e eventos que precisam de um espaço reservado para poses e troca de acessórios com mais privacidade em grupo.",
    features: ["Amplo espaço interno", "Fotos em grupo", "Privacidade para poses e acessórios"],
    ideal: "Formaturas, festas corporativas, eventos sociais e celebrações com grande volume de convidados.",
    gallery: ["assets/site/cabine-inflavel.webp", "assets/site/cabine-tradicional.webp", "assets/site/portfolio-page-4.webp"],
  },
  {
    slug: "terminal-instagram",
    title: "Terminal Instagram",
    category: "Redes sociais",
    accent: "#e2007a",
    image: "assets/site/terminal-instagram.webp",
    alt: "Terminal Instagram para impressão",
    summary: "Fotos publicadas com hashtag são processadas automaticamente e ficam prontas para retirada.",
    description:
      "Os convidados fotografam com seus próprios celulares, editam e postam a foto no Instagram com a hashtag do evento. As fotos são processadas automaticamente pelo sistema da Eternize e ficam prontas para retirada.",
    features: ["Integração com hashtag", "Processamento automático", "Retirada de fotos no evento"],
    ideal: "Eventos sociais, ativações digitais, campanhas com hashtag, feiras e ações de marca.",
    gallery: ["assets/site/terminal-instagram.webp", "assets/site/totem-mobile.webp", "assets/site/portfolio-page-1.webp"],
  },
];
